import Footer from '@/components/Footer';
import theme from '@/theme/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

async function isSession(): Promise<boolean> {
    const cookieStore = await cookies();
    const sessionId = cookieStore.get('member_id');

    try {
        const response = await fetch('http://localhost:5000/api/session', {
            headers:{
                'Cookie': `sessionId=${sessionId?.value || ''}`
            },
            // キャッシュを無効化
            cache: 'no-store',
        });

        if (response.ok) {
            const data = await response.json();
            return data.isSession;
        }
    } catch (error) {
        console.error('Error checking session:', error);
    }
    return false;
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = isSession();

    if(!session) {
        redirect('/register');
    }

    return (
        <html lang="en">
            <body
                style={{
                    margin: 0,
                    padding: 0,
                    backgroundColor: '#000',
                    width: '100vw',
                    minHeight: '100svh',
                    overflowX: 'hidden',
                }}
            >
                <AppRouterCacheProvider>
                    <CssBaseline />
                    <ThemeProvider theme={theme}>
                        {children}
                        <Footer></Footer>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
