import Footer from '@/components/Footer';
import theme from '@/theme/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { AuthProvider } from './contexts/AuthContexts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" style={{ scrollbarWidth: 'thin', scrollbarColor: '#424242 transparent' }}>
            <body
                style={{
                    margin: 0,
                    padding: 0,
                    backgroundColor: '#000',
                    width: '100vw',
                    minHeight: '100vh', // 100svhから100vhに変更
                    overflowX: 'hidden',
                }}
            >
                <style dangerouslySetInnerHTML={{
                    __html: `
                        ::-webkit-scrollbar {
                            width: 8px;
                        }
                        ::-webkit-scrollbar-track {
                            background: transparent;
                        }
                        ::-webkit-scrollbar-thumb {
                            background: #424242;
                            border-radius: 4px;
                        }
                        ::-webkit-scrollbar-thumb:hover {
                            background: #616161;
                        }
                    `
                }} />
                <AppRouterCacheProvider>
                    <CssBaseline />
                    <ThemeProvider theme={theme}>
                        <AuthProvider>
                            <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
                                <div style={{ flex: 1 }}>
                                    {children}
                                </div>
                                <Footer />
                            </div>
                        </AuthProvider>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
