// チャート表示レイアウト
import theme from '@/theme/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { getCookie } from '@/lib/utils/getCookie';
import MainLayoutClient from './MainLayoutClient';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export type UserInfo = {
    id: number;
    emailAddress: string;
};

export default async function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookie = await getCookie('all');
    console.log('cookie', cookie);
    
    // ユーザー認証チェック
    const authResponse = await fetch('http://127.0.0.1:3000/api/proxy?endPoint=/users/auth/user-info/', {
        cache: 'no-store',
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
            cookie: cookie,
        },
    });

    if (!authResponse.ok) {
        redirect('/register');
    }

    // ユーザー情報を取得
    let userInfo: UserInfo | null = null;
    try {
        const userResponse = await fetch('http://127.0.0.1:3000/api/proxy?endPoint=/users/auth/user-info/', {
            cache: 'no-store',
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                cookie: cookie,
            },
        });

        if (userResponse.ok) {
            userInfo = await userResponse.json();
            console.log('userInfo', userInfo);
        }
    } catch (error) {
        console.error('Error fetching user info:', error);
    }

    return (
        <AppRouterCacheProvider>
            <CssBaseline />
            <ThemeProvider theme={theme}>
                <MainLayoutClient userInfo={userInfo}>
                    {children}
                </MainLayoutClient>
            </ThemeProvider>
        </AppRouterCacheProvider>
    );
}
