// チャート表示レイアウト
import theme from '@/theme/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { ApiClient } from '@/lib/api/apiClient';
import { redirect } from 'next/navigation';
const apiClient = new ApiClient

const isSession = async() => {
    const response = await apiClient.request('/users/auth/user-info/', 'GET')
    if(response.ok){
        return
    }else if(response.status == 403) {
        console.log('forbidden')
        redirect('/register')
    }else {
    console.log("予期せぬエラー",response)
    }
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    isSession()
    return (
        <AppRouterCacheProvider>
            <CssBaseline />
            <ThemeProvider theme={theme}>
                {children}
            </ThemeProvider>
        </AppRouterCacheProvider>
    );
}
