import Footer from '@/components/Footer';
import theme from '@/theme/theme';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

async function isSession(): Promise<boolean> {
    const cookieStore = await cookies();
    const sessionId = cookieStore.get('member_id');

    if (!sessionId) {
        console.log('[isSession] No member_id cookie found. Returning false.');
        return false;
    }

    try {
        const response = await fetch('http://localhost:5000/api/session', {
            headers:{
                'Cookie': `sessionId=${sessionId?.value || ''}`
            },
            // キャッシュを無効化
            cache: 'no-store',
        });

        if (response.ok) {
            const data = await response.json();
            return data.isSession;
        }
    } catch (error) {
        console.error('Error checking session:', error);
    }
    console.log('[isSession] Error occurred while checking session. Returning false.');
    return false;
}

export default async function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await isSession();

    if(!session) {
        console.log('redirecting')
        redirect('/register');
    }

    return (
        <AppRouterCacheProvider>
            <CssBaseline />
            <ThemeProvider theme={theme}>
                {children}
                <Footer></Footer>
            </ThemeProvider>
        </AppRouterCacheProvider>
    );
}
